name = "LibTeXPrintf"
uuid = "f5e74093-75df-45cb-9a4a-089f0fae2cb7"
authors = ["José Joaquín Zubieta Rico <jose.zubieta@cimat.mx>"]
version = "0.2.0"

[deps]
LibTeXPrintf_jll = "31c4d84e-4279-5ed4-9345-4512eef47f95"

[compat]
LibTeXPrintf_jll = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
